name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -P /tmp
        unzip /tmp/gradle-7.4.2-bin.zip -d /tmp
        export PATH=$PATH:/tmp/gradle-7.4.2/bin
        gradle -v  # 确保 Gradle 正常安装

    - name: Build APK
      run: |
        cd android  # 进入 Android 项目目录（根据需要修改）
        gradle assembleRelease  # 使用 Gradle 构建 APK

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk  # 根据实际路径修改
