name: Build HarmonyOS APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install HarmonyOS Build Tools (Automatically)
      run: |
        wget https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V3/deveco-linux.zip -P /tmp
        unzip /tmp/deveco-linux.zip -d /tmp
        sudo mv /tmp/deveco /opt/
        export PATH=$PATH:/opt/deveco/bin

    - name: List files in the working directory
      run: |
        ls -la

    - name: Build HarmonyOS Project
      run: |
        cd your_harmonyos_project_directory
        deveco build --mode release  # 构建项目
        mv your_harmonyos_project_directory/output/*.apk /tmp/harmonyos_apks/  # 移动到指定目录

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: harmonyos-app-release.apk
        path: /tmp/harmonyos_apks/*.apk  # 上传新的目录中的 APK
