name: Build HarmonyOS APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install HarmonyOS Build Tools
      run: |
        wget https://developer.harmonyos.com/cn/docs/documentation/doc-guides/deveco-ubuntu-20200413-4202.zip -P /tmp
        unzip /tmp/deveco-ubuntu-20200413-4202.zip -d /tmp
        sudo mv /tmp/deveco /opt/
        export PATH=$PATH:/opt/deveco/bin

    - name: List files in the working directory
      run: |
        ls -la  # 列出当前目录的文件

    - name: Build HarmonyOS Project
      run: |
        cd your_harmonyos_project_directory  # 进入你的鸿蒙项目目录
        deveco build --mode release  # 使用 DevEco 工具进行构建

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: harmonyos-app-release.apk
        path: your_harmonyos_project_directory/output/*.apk  # 根据输出路径调整
